server:
  port: 8033

spring:
  data:
    elasticsearch:
      cluster-nodes: 81.70.181.205:9300
      cluster-name: es6

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.wyf.popj          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#############################################################
##
## 分页插件配置
##
#############################################################
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true